<?php
<!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
echo "key";
echo getConfigData('merchant_key');
?>
<div class="payment-method" data-bind="css: {'_active': (getCode() == isChecked())}">
    <div class="payment-method-title field choice">
        <input type="radio"
               name="payment[method]"
               class="radio"
               data-bind="attr: {'id': getCode()}, value: getCode(), checked: isChecked, click: selectPaymentMethod, visible: isRadioButtonVisible()"/>
        <label class="label" data-bind="attr: {'for': getCode()}">
            <span data-bind="text: getTitle()"></span>
        </label>
    </div>

    <div class="payment-method-content">
        <!-- ko foreach: getRegion('messages') -->
        <!-- ko template: getTemplate() --><!-- /ko -->
        <!--/ko-->
        <div class="payment-method-billing-address">
            <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
            <!-- ko template: getTemplate() --><!-- /ko -->
            <!--/ko-->
        </div>
        <div class="field required">
            <label data-bind="attr: {for: getCode() + '_transaction_result'}" class="label">
                <span><!-- ko i18n: 'Transaction Result'--><!-- /ko --></span>
            </label>

            <div class="control">
<!-- 
                <select name="payment[transaction_result]"
                        class="select"
                        data-bind="
                                  options: getTransactionResults(),
                                  optionsValue: 'value',
                                  optionsText: 'transaction_result',
                                  optionsCaption: $t('Transaction Result'),
                                  value: transactionResult">
                </select> -->
            <?php  echo $block->getMethod()->getMerchant_key(); ?>
            </div>
        </div>

        <div class="actions-toolbar">
        <button id="botonClipClap"></button>
            <div class="primary">
                <!-- <button class="action primary checkout"
                        type="submit"
                        data-bind="
                        click: placeOrder,
                        attr: {title: $t('Place Order')}
                        ">
                    <span data-bind="i18n: 'Place Order'"></span>
                </button> -->
            </div>
        </div>
    </div>
</div>
<!-- BEGIN clipclap CODE -->

  <script type="text/x-magento-init">
        {
            "*": {
                "Magento_ClipClapGateway/js/view/payment/clipclap_gateway": {
                    "merchant_key": "<?php /* @escapeNotVerified */ echo 'keyfrom user' ?>",
                    "iva":  "<?php /* @escapeNotVerified */ echo 'iva user' ?>",
                    "buton_type": <?php echo 'boton tema' ?>
                }
            }
        }
</script>
<!-- END clipclap CODE -->
